[mgr]
show_hidden = true

[opener]
edit = [
  { run = "hx %s", block = true, desc = "Helix" },
]
edit-pane = [
  { run = "zellij run --name helix -- hx %s", block = false, desc = "Helix (Zellij pane)" },
]
