# https://docs.helix-editor.com/configuration.html


# == customize configuration
# 1. `hx -c $path_to_custom_config.toml`
# 2. $PROJECT_ROOT/.helix/
# 3. $XDG_CONFIG_HOME/.helix/
# https://github.com/helix-editor/helix/pull/5748
# https://github.com/helix-editor/helix/issues/5919

theme = "catppuccin_latte"


[editor]

# for the theme under WSL2 in Windows Terminal may occur into error:
# https://github.com/helix-editor/helix/discussions/8031
true-color = true

line-number = "relative"
mouse = false


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.file-picker]
hidden = false

# how to handle buffer conflicting with externally formatting cli
# https://docs.helix-editor.com/editor.html#editorauto-save-section
# https://github.com/helix-editor/helix/issues/1125
# https://github.com/helix-editor/helix/pull/2653
# [editor.auto-save]
# after-delay.enable = true


# https://docs.helix-editor.com/command-line.html
# https://docs.helix-editor.com/commands.html
# https://github.com/sxyazi/yazi/pull/2461
# 
# known issues:
#   1. fzf https://github.com/sxyazi/yazi/issues/2954
[keys.normal]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

# end of file
